# Generated by Django 4.2.1 on 2023-05-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.ManyToManyField(to='relations.account'),
        ),
    ]
