# Generated by Django 4.2.1 on 2023-05-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0004_product_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterField(
            model_name='product',
            name='account',
            field=models.ManyToManyField(to='relations.account', verbose_name='Hesaplar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=64, verbose_name='Ürün Adı'),
        ),
    ]
